openapi: 3.0.0
tags:
  - name: Users
    description: User management endpoints

components:
  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
        email:
          type: string
          format: email
          example: "user@example.com"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        role:
          type: string
          enum: [USER, ADMIN, SUPER_ADMIN]
          example: "USER"
    ProfileResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Profile retrieved successfully"
        data:
          $ref: '#/components/schemas/UserProfile'
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
        errors:
          type: object
          properties:
            code:
              type: string
            details:
              type: object

paths:
  /api/users/profile:
    get:
      summary: Get user profile
      description: Retrieves the profile information of the authenticated user. Requires a valid authentication token.
      tags: [Users]
      security:
        - bearerAuth: []
      responses:
        200:
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        401:
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "Unauthorized"
                errors:
                  code: "INVALID_TOKEN"
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "User not found"
                errors:
                  code: "VALIDATION_ERROR"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                success: false
                message: "Internal server error" 